data_set = {
    'один': 'passive 1',
    'раз': 'passive 1',
    'единица': 'passive 1',
    'два': 'passive 2',
    'двойка': 'passive 2',
    'три': 'passive 3',
    'тройка': 'passive 3',
    'четыре': 'passive 4',
    'четверка': 'passive 4',
    'пять': 'passive 5',
    'пятерка': 'passive 5',
    'шесть': 'passive 6',
    'шестерка': 'passive 6',
    'семь': 'passive 7',
    'сетерка': 'passive 7',
    'восемь': 'passive 8',
    'восьмерка': 'passive 8',
    'девять': 'passive 9',
    'девятка': 'passive 9',
    'десять': 'passive 10',
    'десятка': 'passive 10',
    'стоп модель': 'passive Стоп',
    }
